ALTER TABLE regioes_atendimento DROP CONSTRAINT ck_regioes_atendimento_tipo;

ALTER TABLE regioes_atendimento
    ADD CONSTRAINT ck_regioes_atendimento_tipo CHECK (tipo IN ('BAIRRO', 'CIDADE'));

INSERT INTO regioes_atendimento (nome, tipo, ativo)
SELECT v.nome, v.tipo, TRUE
FROM (
    VALUES
        ('Aberta dos Morros', 'BAIRRO'),
        ('Agronomia', 'BAIRRO'),
        ('Anchieta', 'BAIRRO'),
        ('Arquipélago', 'BAIRRO'),
        ('Auxiliadora', 'BAIRRO'),
        ('Azenha', 'BAIRRO'),
        ('Bela Vista', 'BAIRRO'),
        ('Belém Novo', 'BAIRRO'),
        ('Belém Velho', 'BAIRRO'),
        ('Boa Vista', 'BAIRRO'),
        ('Boa Vista do Sul', 'BAIRRO'),
        ('Bom Jesus', 'BAIRRO'),
        ('Bom Fim', 'BAIRRO'),
        ('Camaquã', 'BAIRRO'),
        ('Campo Novo', 'BAIRRO'),
        ('Cascata', 'BAIRRO'),
        ('Cavalhada', 'BAIRRO'),
        ('Centro', 'BAIRRO'),
        ('Chácara das Pedras', 'BAIRRO'),
        ('Chapéu do Sol', 'BAIRRO'),
        ('Cidade Baixa', 'BAIRRO'),
        ('Coronel Aparício Borges', 'BAIRRO'),
        ('Costa e Silva', 'BAIRRO'),
        ('Cristal', 'BAIRRO'),
        ('Cristo Redentor', 'BAIRRO'),
        ('Espírito Santo', 'BAIRRO'),
        ('Extrema', 'BAIRRO'),
        ('Farrapos', 'BAIRRO'),
        ('Farroupilha', 'BAIRRO'),
        ('Floresta', 'BAIRRO'),
        ('Glória', 'BAIRRO'),
        ('Guarujá', 'BAIRRO'),
        ('Higienópolis', 'BAIRRO'),
        ('Hípica', 'BAIRRO'),
        ('Humaitá', 'BAIRRO'),
        ('Independência', 'BAIRRO'),
        ('Ipanema', 'BAIRRO'),
        ('Jardim Botânico', 'BAIRRO'),
        ('Jardim Carvalho', 'BAIRRO'),
        ('Jardim Dona Leopoldina', 'BAIRRO'),
        ('Jardim Floresta', 'BAIRRO'),
        ('Jardim Isabel', 'BAIRRO'),
        ('Jardim Europa', 'BAIRRO'),
        ('Jardim Itu', 'BAIRRO'),
        ('Jardim Sabará', 'BAIRRO'),
        ('Jardim Lindóia', 'BAIRRO'),
        ('Jardim do Salso', 'BAIRRO'),
        ('Jardim São Pedro', 'BAIRRO'),
        ('Lageado', 'BAIRRO'),
        ('Lami', 'BAIRRO'),
        ('Lomba do Pinheiro', 'BAIRRO'),
        ('Mário Quintana', 'BAIRRO'),
        ('Medianeira', 'BAIRRO'),
        ('Menino Deus', 'BAIRRO'),
        ('Moinhos de Vento', 'BAIRRO'),
        ('Mont''Serrat', 'BAIRRO'),
        ('Morro Santana', 'BAIRRO'),
        ('Navegantes', 'BAIRRO'),
        ('Nonoai', 'BAIRRO'),
        ('Parque Santa Fé', 'BAIRRO'),
        ('Partenon', 'BAIRRO'),
        ('Passo D''Areia', 'BAIRRO'),
        ('Passo das Pedras', 'BAIRRO'),
        ('Pedra Redonda', 'BAIRRO'),
        ('Petrópolis', 'BAIRRO'),
        ('Pitinga', 'BAIRRO'),
        ('Ponta Grossa', 'BAIRRO'),
        ('Praia de Belas', 'BAIRRO'),
        ('Restinga', 'BAIRRO'),
        ('Rio Branco', 'BAIRRO'),
        ('Rubem Berta', 'BAIRRO'),
        ('Santa Cecília', 'BAIRRO'),
        ('Santa Maria Goretti', 'BAIRRO'),
        ('Santa Rosa de Lima', 'BAIRRO'),
        ('Santa Tereza', 'BAIRRO'),
        ('Santana', 'BAIRRO'),
        ('Santo Antônio', 'BAIRRO'),
        ('São Caetano', 'BAIRRO'),
        ('São Geraldo', 'BAIRRO'),
        ('São João', 'BAIRRO'),
        ('São Sebastião', 'BAIRRO'),
        ('Sarandi', 'BAIRRO'),
        ('Serraria', 'BAIRRO'),
        ('Sétimo Céu', 'BAIRRO'),
        ('Teresópolis', 'BAIRRO'),
        ('Três Figueiras', 'BAIRRO'),
        ('Tristeza', 'BAIRRO'),
        ('Vila Assunção', 'BAIRRO'),
        ('Vila Conceição', 'BAIRRO'),
        ('Vila Ipiranga', 'BAIRRO'),
        ('Vila Jardim', 'BAIRRO'),
        ('Vila João Pessoa', 'BAIRRO'),
        ('Vila Nova', 'BAIRRO'),
        ('Vila São José', 'BAIRRO'),
        ('Tramandaí', 'CIDADE'),
        ('Capão da Canoa', 'CIDADE'),
        ('Xangri-lá', 'CIDADE')
) AS v(nome, tipo)
WHERE NOT EXISTS (
    SELECT 1
    FROM regioes_atendimento r
    WHERE r.nome = v.nome
);
